name: CI

on: [push, workflow_dispatch]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v4

      - name: Get dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test

      - name: Build
        run: npm run build

      - name: Deploy
        run: echo "Deploying..."
